# Generated by Django 6.0.3 on 2026-04-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hexgame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='kick_if_inactive',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='minutes_per_turn',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
