# Generated by Django 6.0.3 on 2026-04-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hexgame', '0002_game_kick_if_inactive_game_minutes_per_turn'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField(unique=True)),
                ('p256dh', models.TextField()),
                ('auth', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
