# Generated by Django 6.0.3 on 2026-04-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hexgame', '0004_pushsubscription_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='turn_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
