# Generated by Django 6.0.3 on 2026-04-27 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hexgame', '0005_game_turn_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GameEvent',
            new_name='PlayerEvent',
        ),
    ]
