# Generated by Django 6.0.3 on 2026-04-27 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hexgame', '0006_rename_gameevent_playerevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerevent',
            old_name='timestsamp',
            new_name='timestamp',
        ),
    ]
