# Generated by Django 6.0.3 on 2026-04-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hexgame', '0007_rename_timestsamp_playerevent_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
