# Generated by Django 6.0.3 on 2026-05-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hexgame', '0011_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='difficulty',
            field=models.CharField(choices=[('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard'), ('I', 'Impossible')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='game',
            name='spectatable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='game',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
