# Generated by Django 6.0.3 on 2026-05-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hexgame', '0012_game_spectatable_game_title_alter_game_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='difficulty',
            field=models.CharField(choices=[('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard'), ('I', 'Impossible')], default='M'),
        ),
    ]
