# Generated by Django 6.0.3 on 2026-05-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hexgame', '0014_game_creator_alter_game_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='forfeited',
            field=models.BooleanField(default=False),
        ),
    ]
